services:
  curio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curio
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "2000:2000"
      - "5002:5002"
      - "8080:8080"
    volumes:
      - ./templates:/app/templates
      - ./data:/app/data