name: Publish to PyPI on Release

on:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write

jobs:
  build-and-publish:
    name: Build and Upload to PyPI
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: 📦 Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'

    - name: 📁 Install and build utk-ts frontend
      run: |
        npm install
        npm run build
      working-directory: ./utk_curio/frontend/utk-workflow/src/utk-ts

    - name: 📁 Install and build urban-workflows frontend
      run: |
        npm install
        npm run build
      working-directory: ./utk_curio/frontend/urban-workflows

    - name: 🧪 Extract version from GitHub Release tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Extracted version: $VERSION"
        echo "__version__ = \"$VERSION\"" > utk_curio/__init__.py

    - name: 📦 Install build backend
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel

    - name: 🧹 Clean previous builds
      run: rm -rf dist/ *.egg-info

    - name: 🛠 Build sdist and wheel
      run: python -m build --no-isolation
    
    - name: Check wheel metadata
      run: |
          twine check dist/*

    - name: 📦 Debug Wheel Contents
      run: unzip -l dist/*.whl

    - name: 🚀 Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: 📎 Upload artifacts to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
